# Generated by Django 3.0.5 on 2020-05-18 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_report_created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='pdf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CallReportTraffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('traffic_place', models.CharField(max_length=64)),
                ('traffic_income', models.BooleanField(default=False)),
                ('traffic_name', models.CharField(max_length=32)),
                ('traffic_int_volume', models.IntegerField(null=True)),
                ('traffic_sec_volume', models.IntegerField(null=True)),
                ('traffic_other_volume', models.IntegerField(null=True)),
                ('call_report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kombain_service.CallReport')),
            ],
        ),
    ]
